openapi: 3.0.0
servers:
  - url: https://api-testnet.bybit.com
    description: Testnet server
info:
  description: |
    Collection of v5 Restul API
  version: 3.0.0
  title: Bybit Open API v5 explorer
tags:
  - name: account
    description: Account endpoints
    x-displayName: Account
x-tagGroups:
  - name: private
    tags:
      - account
paths:
  /v5/account/wallet-balance:
    get:
      tags:
        - account
      summary: Get Wallet Balance
      description: Get wallet balance
      operationId: wallet
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: accountType
          in: query
          description: Account type
          required: true
          schema:
            type: string
            enum:
              - UNIFIED
              - CONTRACT
              - SPOT
        - name: coin
          in: query
          description: Coin name. You can pass mutiple coins like USDT,USDC
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/account/upgrade-to-uta:
    post:
      tags:
        - account
      summary: Upgrade to Unified Account
      description: Upgrade to UTA
      operationId: upgrade-unified-account
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object

  /v5/account/set-collateral-switch:
    post:
      tags:
        - account
      summary: Set Collateral Coin
      description: Set collateral coin
      operationId: set-collateral
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                coin:
                  type: string
                  description: coin
                  example: BTC
                collateralSwitch:
                  type: string
                  description: coin
                  example: ON
                  enum:
                    - ON
                    - OFF
              required:
                - coin
                - collateralSwitch
  /v5/account/borrow-history:
    get:
      tags:
        - account
      summary: Get Borrow History
      description: Get borrow history
      operationId: borrow-history
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: currency
          in: query
          description: e.g., USDC, USDT, BTC, ETH
          required: false
          schema:
            type: string
        - name: startTime
          in: query
          description: The start timestamp (ms)
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: The end timestamp (ms)
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Limit per page. 1-50
          required: false
          schema:
            type: integer
            default: 20
        - name: cursor
          in: query
          description: Cusor, used for pagiation
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /v5/account/collateral-info:
    get:
      tags:
        - account
      summary: Get Collateral Info
      description: Get collateral info
      operationId: collateral-info
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: currency
          in: query
          description: Collateral asset
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /v5/account/coin-greeks:
    get:
      tags:
        - account
      summary: Get Coin Greeks
      description: Get coin greek info
      operationId: coin-greeks
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: baseCoin
          in: query
          description: Base coin
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
  /v5/account/fee-rate:
    get:
      tags:
        - account
      summary: Get Fee Rate
      description: Get fee rate
      operationId: fee-rate
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: category
          in: query
          description: Product type. working for spot and option
          required: true
          schema:
            type: string
            enum:
              - spot
              - linear
              - inverse
              - option
        - name: symbol
          in: query
          description: Symbol name. valid for linear,inverse and spot
          required: false
          schema:
            type: string
        - name: baseCoin
          in: query
          description: Base coin. Valid for option
          required: false
          schema:
            type: string
            enum:
              - SOL
              - BTC
              - ETH
      responses:
        "200":
          description: successful operation

  /v5/account/info:
    get:
      tags:
        - account
      summary: Get Account Info
      description: Get account info
      operationId: account-info
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /v5/account/transaction-log:
    get:
      tags:
        - account
      summary: Get Transaction Log
      description: Get transaction log
      operationId: transaction-log
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: accountType
          in: query
          description: Support `UNIFIED` for now
          required: false
          schema:
            type: string
            enum:
              - UNIFIED
        - name: category
          in: query
          description: Product category
          required: false
          schema:
            type: string
            enum:
              - spot
              - linear
              - option
        - name: currency
          in: query
          description: Currency
          required: false
          schema:
            type: string
        - name: baseCoin
          in: query
          description: Base coin
          required: false
          schema:
            type: string
        - name: type
          in: query
          description: Transaction log type
          required: false
          schema:
            type: string
            enum:
              - TRANSFER_IN
              - TRANSFER_OUT
              - TRADE
              - SETTLEMENT
              - DELIVERY
              - LIQUIDATION
              - BONUS
              - FEE_REFUND
              - INTEREST
              - CURRENCY_BUY
              - CURRENCY_SELL
        - name: startTime
          in: query
          description: The start timestamp (ms)
          required: false
          schema:
            type: integer
        - name: endTime
          in: query
          description: The end timestamp (ms)
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: Limit size for each page. 1-50
          required: false
          schema:
            type: integer
            default: 20
        - name: cursor
          in: query
          description: Cursor, used for pagination
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation

  /v5/account/set-margin-mode:
    post:
      tags:
        - account
      summary: Set Margin Mode
      description: Set margin mode
      operationId: set-margin-mode
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                setMarginMode:
                  type: string
                  description: Margin mode
                  enum:
                    - REGULAR_MARGIN
                    - ISOLATED_MARGIN
                    - PORTFOLIO_MARGIN
                  example: PORTFOLIO_MARGIN
              required:
                - setMarginMode
  /v5/account/set-hedging-mode:
    post:
      tags:
        - account
      summary: Set Spot Hedging
      description: Set spot hedging for Portfolio margin
      operationId: set-spot-hedge
      parameters:
        - name: apiKey
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
        - name: secret
          in: header
          description: A UTA sub account API key is provided by default
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                setHedgingMode:
                  type: string
                  description: on or off spot hedging mode
                  enum:
                    - ON
                    - OFF
                  example: ON
              required:
                - setHedgingMode