/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  bbyPaySideBar: [
    'api-overview',
    {
      type: 'category',
      label: 'QR Payment',
      collapsed: false,
      items: [
        'scan-payment/introduction',
        'scan-payment/guide',
        'scan-payment/flow',
        'scan-payment/user-guide',
        'scan-payment/order-status',
        'scan-payment/create-payment',
        'scan-payment/payment-result',
        'scan-payment/payment-notify',
        'scan-payment/payment-fx-convert',
        'scan-payment/payment-status-mock',
        'scan-payment/refund',
        'scan-payment/payout',
        'scan-payment/settlement',
        {
          type: 'category',
          label: 'Data Models',
          items: [
            {
              type: 'autogenerated',
              dirName: 'scan-payment/data-model'
            }
          ]
        },
        'scan-payment/mcc-codes',
        'scan-payment/sign-algo',
        'scan-payment/error',
      ]
    },
    {
      type: 'category',
      label: 'Recurring Payments',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'recurring-payments'
        }
      ]
    },
  ],
  changelogSidebar: [
    "changelog/bybit-pay"
  ]
};

module.exports = sidebars;
