/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  bbyPaySideBar: [
    'bybit-pay/guide',
    'bybit-pay/flow',
    'bybit-pay/user-guide',
    'bybit-pay/order-status',
  {
    type: 'category',
    label: 'Scan Payment',
    items: [
      {
        type: 'autogenerated',
        dirName: 'bybit-pay/scan-payment'
      }
    ]
  },
  'bybit-pay/refund',
  'bybit-pay/payout',
  {
    type: 'category',
    label: 'Data Models',
    items: [
      {
        type: 'autogenerated',
        dirName: 'bybit-pay/data-model'
      }
    ]
  },
  'bybit-pay/mcc-codes',
  'bybit-pay/sign-algo',
  'bybit-pay/error',
],
  changelogSidebar: [
    "changelog/v5"
  ]
};

module.exports = sidebars;
